### ISSUE TITLE
A way to see who reacted

### ISSUE THREAD

**Issue by daath** [gdpelican/retort#42]
My users have requested a way to see who has reacted - Doing mouse-over reveals a couple of names, but not the rest - Clicking it just reacts - Holding LMB on the icon reveals the same couple of names...

Thanks! :)

**Comment by IwishIcanFLighT** [comment]
Hi!

I would also be very interested for the same reasons as @daath stated. :+1:

**Comment by wolftune** [comment]
Would be clearer if title were edited to say "**all** who reacted"

**Comment by GokulNC** [comment]
@IwishIcanFLighT Can you please make a pull request with the changes you said?

**Comment by IwishIcanFLighT** [comment]
@GokulNC Sorry I never got the time to actually make this change and no longer need it for my discourse instance.

In the meantime from what I found it looks like my previous suggestion cannot be applied anymore as the plugin seems to support different locales now:
https://github.com/gdpelican/retort/blob/7fd191b7e47a9612163436556e14ed1cd1b313ac/config/locales/client.en.yml
```
en:
  js:
    retort:
      title: 'add an emoji reaction to this post'
      reactions:
        one_person:  "%{first} reacted with :%{emoji}:"
        two_people:  "%{first} and %{second} reacted with :%{emoji}:"
        many_people: "%{first}, %{second}, and %{count} others reacted with :%{emoji}:"
```

I suppose you'd also need to modify the code in this file as well:
https://github.com/gdpelican/retort/blob/8d582c512ae89427c6e0520f9f256e91c05aa07b/assets/javascripts/discourse/widgets/retort-toggle.js.es6

```
  sentence({ usernames, emoji }) {
    let key
    switch(usernames.length) {
      case 1: key = 'retort.reactions.one_person'; break
      case 2: key = 'retort.reactions.two_people'; break
      default: key = 'retort.reactions.many_people'; break
    }
```
